name: Build & Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        env:
          GIT_SSL_NO_VERIFY: "true"

      - name: Verify Docker
        run: docker info

      - name: Set up Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login \
            ${{ secrets.REGISTRY_URL }} \
            -u "${{ secrets.REGISTRY_USERNAME }}" \
            --password-stdin
        env:
          GIT_SSL_NO_VERIFY: "true"

      - name: Build & push
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f Dockerfile.prod \
            -t ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:latest \
            --push .
        env:
          GIT_SSL_NO_VERIFY: "true"
